#!/bin/bash

### BEGIN INIT INFO
# Provides: BoardControl
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

NAME=BoardControl
APP=/opt/BoardControl/app.js
forever=/usr/bin/forever
export PATH=$PATH:/usr/bin/

case "$1" in
  start)
  echo "Starting $NAME at path &APP"
  $forever start $APP
    ;;
  stop)
  echo "Stopping $NAME at path &APP"
  $forever stop $APP
    ;;
  list)
  echo "List of instance running on forever"
  $forever list
    ;;
  *)
    echo "Usage: /etc/init.d/boardcontrol {start|stop|list}"
    exit 1
    ;;
esac

exit 0